configfile: "../config/config_targets.yaml"
workdir: config["workdir"]
config["result_dir"] = f"{config['workdir']}/{config['result_dirname']}"

include: "rules/1_preprocess.smk"
include: "rules/2_ASRstep.smk"
include: "rules/3_BINARYmsa.smk"
include: "rules/3_BINARYstep.smk"
include: "rules/4_GapAWAREstep.smk"
include: "rules/5_GapAWAREscore.smk"


all_nt_norms = config["nt_norms"]

query_ids_file = config["query_ids_file"]
with open(query_ids_file) as f:
    query_ids = [line.strip() for line in f if line.strip()]

rule all:
    input:
        expand("{result_dir}/{query_id}/4_gapAware_scores_{nt_norm}/{query_id}_wl_param_{pattern}.csv",
               result_dir=config["result_dir"],
               query_id=query_ids,
               pattern=config["pattern"],
               nt_norm=all_nt_norms
              ),
        expand("{result_dir}/{query_id}/4_gapAware_scores_{nt_norm}/{query_id}_wol_param_{pattern}.csv",
               result_dir=config["result_dir"],
               query_id=query_ids,
               pattern=config["pattern"],
               nt_norm=all_nt_norms
              )

