configfile: "config/config_targets.yaml"

workdir: "../workflow_targets"

query_ids_file: "test/query_ids.txt"
result_dirname: "results"

msa_file_pattern: "test/{query_id}.fasta"
tree_file_path: "470mammals_tree.nwk"


query_species: "hg38"

nt_norms:
  - "NN"
  - "FN"


#IQ-TREE
iqtree_ancestral_model: "scripts/notr_model.txt"
#iqtree_ancestral_model: GTR+G
iqtree_seed: "777"

#RAXMLNG
raxml_model: "GTR{scripts/notr_model.txt}+R4"
raxml_seed: "777"


#SCORE COMPUTATION
#weights: "0.1,0.5,0,1,2,3,5,mean,median,X,CountNodes_1,CountNodes_2,CountNodes_3,CountNodes_4,0_MinNode_Mix,0_MinNode_Mix2"
weights: "0"

pattern: ["0"]
