configfile: "config/config_ortholog.yaml"
workdir: "../workflow_orthologs" # working directory for the workflow
query_ids_file: "test/input_mirna.txt" # input file containing the query IDs (one per line)
score_result_dirname: "mirna_score_results" # directory name for the score results
id_prefix: "_pri" #primary miRNA ID prefix for the query IDs in the input file
consensus_tree: "consensus_timetree.nwk" # consensus tree file
alignment_pattern: "test/{query_id}_annotated.aln" # alignment file pattern for the query IDs in the input file

# two type of normalization methods
# NN: Normalized by the number of nodes in the tree
# FN: Normalized by the frequency of the query nucleotide in the alignment
nt_norms:
  - "NN"
  - "FN"

#RAXMLNG
raxml_model: "GTR{scripts/notr_model.txt}+R4"
raxml_seed: "777"

#SCORE CALCULATION
weights: "0.1,0.5,0,1,2,3,5,mean,median,X,CountNodes_1,CountNodes_2,CountNodes_3,CountNodes_4,0_MinNode_Mix,0_MinNode_Mix2"
pattern: ["0"]
